FROM node:lts-slim
WORKDIR /project/
COPY frontend .

RUN apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg && echo "deb http://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list && apt-get update && apt-get install -y yarn --allow-unauthenticated && yarn global add webpack && yarn && npm run build


FROM nginx:stable-alpine
COPY nginx/nginx-prod.conf /etc/nginx/nginx.conf
COPY --from=0 /project/dist /frontend/dist
COPY --from=0 /project/dist-html /frontend/dist-html
COPY /var/ssl /ssl
