FROM node:lts-alpine AS frontend
WORKDIR /project
COPY frontend .

RUN npm install && npm run build


FROM staticfloat/nginx-certbot

COPY nginx/conf.d /etc/nginx/user.conf.d

COPY --from=frontend /project/dist            /content
