"""add currency_metabolites table

Revision ID: a12086482044
Revises: None
Create Date: 2016-05-11 15:37:22.182010

"""

# revision identifiers, used by Alembic.
revision = 'a12086482044'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency_metabolites',
    sa.Column('component_id', sa.String(length=50), nullable=False),
    sa.Column('reaction_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['reaction_component.id'], ),
    sa.ForeignKeyConstraint(['reaction_id'], ['reaction.id'], ),
    sa.PrimaryKeyConstraint('component_id', 'reaction_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('currency_metabolites')
    ### end Alembic commands ###
