export default {
  en: {
    searchPlaceholder: 'Search by metabolite (uracil), gene (SULT1A3), or reaction (ATP[c] => cAMP[c] + PPi[c])',
    searchNoResult: 'No result found',
    footerText: 'Chalmers University of Technology | Department of Biology and Biological Engineering | <a href="http://sysbio.se" target="blank">Sys<sup>2</sup>Bio</a>',
    moreInformation: 'More information',
    connectedMetabolites: {
      instructions: 'Click on a reaction component for more details.',
    },
    tableSearchPlaceholder: 'Search in table',
    tooManyReactions: 'There are too many reactions to be displayed in a graph (> 10). Here is a list of all the reactions.',
    tooManyReactionsWarn: 'Warning: The query has returned too many reactions.<br>The graph has not been generated.',
    tooManyReactionsBut: 'Show it anyway!',
    tooManyInteractionPartners: 'There are too many interaction partners to be displayed in a graph.',
    navBut1Title: 'Network graph',
    navBut2Title: 'Models',
    navBut3Title: 'Resources',
    navBut4Title: 'About',
    navBut5Title: 'Contact',
    human: 'Human',
    yeast: 'Yeast',
    reset: 'Reset',
    export: 'Export',
    tab1title: 'The whole metabolic network',
    tab2title: 'Zoom in on region',
    tab3title: 'Closest interaction partners',
    tab4title: 'Catalysed reactions',
    tab5title: 'Metabolites',
    tab6title: 'Pathways',
    notFoundError: 'No matching record found, please check the parameters and try again.',
    unknownError: 'Something went wrong, please try again or contact the system admin.',
    noInfoAvailable: 'No information available',
    noIDProvided: 'No ID provided',
  },
};
