export default {
  en: {
    searchPlaceholder: 'Search by metabolite (uracil), gene (SULT1A3), or reaction (ATP[c] => cAMP[c] + PPi[c])',
    searchNoResult: 'No result found',
    footerText: 'Chalmers University of Technology | Department of Biology and Biological Engineering | <a href="http://sysbio.se" target="blank">Sys<sup>2</sup>Bio</a>',
    moreInformation: 'More information',
    connectedMetabolites: {
      instructions: 'Click on a reaction component for more details.',
    },
    tableSearchPlaceholder: 'Search in table',
    tooManyReactions: 'There are too many reactions to be displayed in a graph (> 10). Here is a list of all the reactions.',
    tooManyReactionsTable: 'The number of reactions displayed is limited to 200, some may have been discarded.',
    tooManyReactionsWarn: 'Warning: The query has returned too many reactions.<br>The graph has not been generated.',
    tooManyReactionsBut: 'Show it anyway!',
    tooManyInteractionPartners: 'There are too many interaction partners to be displayed in a graph.',
    navBut1Title: 'GEM visualisation',
    navBut2Title: 'Models',
    navBut3Title: 'Tools',
    navBut4Title: 'Databases',
    navBut5Title: 'About',
    navBut6Title: 'Help',
    navBut7Title: 'Contact',
    human: 'HMR 2.0',
    yeast: 'Yeast 7.6',
    reset: 'Reset',
    exportButton: 'Export to Excel',
    tab1title: 'The whole metabolic network',
    tab2title: 'Closest interaction partners',
    tab3title: 'Enzyme page',
    tab4title: 'Metabolite page',
    tab5title: 'Reaction page',
    tab6title: 'Subsystem',
    notFoundError: 'No matching record(s) found, please check the parameters and try again.',
    unknownError: 'Something went wrong, please try again or contact the system admin.',
    noInfoAvailable: 'No information available',
    noIDProvided: 'No ID provided',
  },
};
