export default {
  en: {
    searchPlaceholder: 'Search by metabolite (uracil), gene (SULT1A3), or reaction (ATP => cAMP + PPi) or subsystem',
    searchNoResult: 'No results found',
    footerText: 'Chalmers University of Technology | Department of Biology and Biological Engineering | <a href="http://sysbio.se" target="blank">Sys<sup>2</sup>Bio</a>',
    moreInformation: 'More information',
    connectedMetabolites: {
      instructions: 'Click on a reaction component for more details.',
    },
    tableSearchPlaceholder: 'Search in table',
    tooManyReactions: 'There are too many reactions to be displayed in a graph (> 10). Here is a list of all the reactions.',
    tooManyReactionsTable: 'The number of reactions displayed is limited to 200, some may have been discarded.',
    tooManyReactionsWarn: 'Warning: The query has returned too many reactions.<br>The graph has not been generated.',
    tooManyReactionsBut: 'Generate',
    tooManyInteractionPartners: 'There are too many interaction partners to be displayed in a graph.',
    navBut1Title: 'GEMs Explorer',
    navBut2Title: 'GEMs',
    navBut3Title: 'Resources',
    navBut31Title: 'Tools',
    navBut32Title: 'External Databases',
    navBut33Title: 'API',
    navBut4Title: 'Documentation',
    navBut5Title: 'About',
    navBut6Title: 'Contact',
    hmr2: 'HMR 2.0',
    ymr: 'Yeast 7.6',
    reset: 'Reset',
    exportButton: 'Export to Excel',
    metabolicViewer: 'Metabolic Viewer',
    tab1title: 'Closest interaction partners',
    tab2title: 'Enzyme page',
    tab3title: 'Metabolite page',
    tab4title: 'Reaction page',
    tab5title: 'Subsystem page',
    notFoundError: 'No matching record(s) found, please check the parameters and try again.',
    unknownError: 'Something went wrong, please try again or contact the system admin.',
    noInfoAvailable: 'No information available',
    noIDProvided: 'No ID provided',
  },
};
